[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "backend"  # Points to your Express backend

[dev]
  framework = "vite"
  targetPort = 5173
  command = "npm run dev"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"  # Routes API calls to backend
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200