[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200