[build]
  command = "npm run build"
  publish = "dist"
  functionsDirectory = "backend/functions"  # If using Netlify Functions

[build.environment]
  NODE_VERSION = "18"

# Environment variables (directly accessible via process.env)
[context.production.environment]
  REACT_APP_FIREBASE_API_KEY = "AIzaSyDq2a_2dZs5wVwcLb8ENx8f_5eeuNLJPd8"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "h2flow-4ab96.firebaseapp.com"
  REACT_APP_FIREBASE_PROJECT_ID = "h2flow-4ab96"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "h2flow-4ab96.appspot.com"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "213685018499"
  REACT_APP_FIREBASE_APP_ID = "1:213685018499:web:f932223d0e3b203e00a0b6"

# Redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200
  force = true